### ISSUE TITLE
error in uni-directional payment channel

### ISSUE THREAD

**Issue by phyBrackets** [solidity-by-example/solidity-by-example.github.io#191]
In the line no. 23 - https://github.com/solidity-by-example/solidity-by-example.github.io/blob/9d1ad735bf76015c565a6b60d710e79ac11dae83/src/pages/app/uni-directional-payment-channel/UniDirectionalPaymentChannel.sol 
Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires **"view"**.
       `return keccak256(abi.encodePacked(address(this), _amount));`

**Comment by t4sk** [comment]
fixed. Thanks
