### ISSUE TITLE
A bug in NFT English Auction code example? 

### ISSUE THREAD

**Issue by tnkrxyz** [solidity-by-example/solidity-by-example.github.io#212]
In the [English auction code](https://github.com/solidity-by-example/solidity-by-example.github.io/blob/gh-pages/src/pages/app/english-auction/EnglishAuction.sol), when a bidder calls bid(), it sends the bid amount (`msg.value`) to the contract address, but in the bid() function the bids array only adds value of the current `highestBid` (before `highestBid` gets set to `msg.value` in line 69). A bidder won't receive a full refund if it withdraws before it wins or gets outbidded by others.

A hypothetical example may help see the bug better: Assuming the auction contract gets initiated with `_startingBid` = 0, when the first bidder bidder1 bids 1 ether for the NFT, `bids[bidder1] = 0` at line 65. If bidder1 withdraws its bid now, it will receive 0 refund from the contract address, even though it sends 1 ether to the contract when calling bid().

The fix is easy, by moving the 3 lines starting at Line 64 to currently Line 70. The winner should also have the bid amount subtract from amount withdrawable.

I created a pull request with fixes & re-generated page.

**Comment by t4sk** [comment]
I wrote the contract with the following restriction.
Highest bidder cannot withdraw the current highest bid.

I don't think there is a bug. Am I wrong?

**Comment by tnkrxyz** [comment]
It still is a bug. Re-use the original example above:

>A hypothetical example may help see the bug better: Assuming the auction contract gets initiated with _startingBid = 0, when the first bidder bidder1 bids 1 ether for the NFT, bids[bidder1] = 0 at line 65. If bidder1 withdraws its bid now, it will receive 0 refund from the contract address, even though it sends 1 ether to the contract when calling bid().

Now another bidder bidder2 bids 2 eth, `bids[bidder2] = 1` at Line 65, but `bids[bidder1]` is never set to 1 (would still `=0`) and bidder1 would not receive any refund.
