### ISSUE TITLE
uint to uint256 (Typo)

### ISSUE THREAD

**Issue by 0xWick** [solidity-by-example/solidity-by-example.github.io#224]
Noticed a slight typo in Primitive Data Types,
Second uint (u256) should be written as uint256

![image](https://user-images.githubusercontent.com/69587947/169165377-8372c85a-8e22-41a9-9b1d-df9914787a09.png)

Second int (i256) should be written as int256

![image](https://user-images.githubusercontent.com/69587947/169165592-95b84a12-b16e-402e-b762-eed12fcfbc8d.png)

**Comment by t4sk** [comment]
My prettier setting auto formats uint256 to uint. I'm not going to fix this
