### ISSUE TITLE
Can we remove safe math ?

### ISSUE THREAD

**Issue by ihorbond** [solidity-by-example/solidity-by-example.github.io#232]
https://solidity-by-example.org/app/bi-directional-payment-channel/ specifies v0.8.13 but import SafeMath. Was it just left over from the pre 0.8.0 code or is it genuinely needed in this particular example ?

**Comment by t4sk** [comment]
It's not needed for 0.8

Can you submit a PR with the code change?

**Comment by ihorbond** [comment]
done @t4sk  #237
