### ISSUE TITLE
Explain why low-level call is not recommeded

### ISSUE THREAD

**Issue by paulrberg** [solidity-by-example/solidity-by-example.github.io#245]
Thanks for creating this website, I frequently return to it when in doubt about how a particular syntax works in Solidity.

Some feedback on the [call](https://solidity-by-example.org/call/) page. You say that:

> ... it is not the recommend way to call existing functions.

But do not explain why.

It might be helpful to add a few thoughts about why using the low-level calls is not recommended. As far as I know, the reasons are:

- Reverts are not bubbled up
- Type checks are bypassed
- Function existence checks are omitted
- No argument packing (though I'm not sure about this point)

**Comment by t4sk** [comment]
done

**Comment by paulrberg** [comment]
Nice, thank you.
