### ISSUE TITLE
`tokens` is never initialized

### ISSUE THREAD

**Issue by YanhuiJessica** [solidity-by-example/solidity-by-example.github.io#258]
https://github.com/solidity-by-example/solidity-by-example.github.io/blob/1e22f13c3c68f489231e0ca0f856b0290bd7a80f/src/pages/defi/stable-swap-amm/StableSwap.sol#L48

The array `tokens` in the StableSwap is never initialized. Is that intended?

**Comment by t4sk** [comment]
fixed. thanks
