### ISSUE TITLE
Outdated echidna examples

### ISSUE THREAD

**Issue by wildanvin** [solidity-by-example/solidity-by-example.github.io#264]
Hello,

The echidna examples in the [repo](https://github.com/solidity-by-example/solidity-by-example.github.io/tree/gh-pages/src/pages/tests/echidna) seem to be outdated. It says to run `echidna-test` instead of just `echidna` as in the [documentation](https://github.com/crytic/echidna/blob/cb197b333408b99172e6935bb27ab95b23c5331a/README.md?plain=1#L48). I got an error when I tried `echidna-test`.

Also there are some minor corrections in the contracts:
- **TestEchidna.sol:**
  - To use assertions you need the flag `--test-mode assertion` instead of  `--check-asserts`
  - echidna in not buggy anymore, so you don't need to switch to solc 0.7 to run assertions
- **EchidnaTestTimeAndCaller.sol:**
  - The third address is `0x30000` instead of `0x00a329C0648769a73afAC7F9381e08fb43DBEA70`

I would be more than happy to create a PR with the corrections but I wanted to confirm with you first if you consider these changes valid.

Cheers.

**Comment by t4sk** [comment]
Please send a PR

**Comment by wildanvin** [comment]
Right away ser 🫡
