### ISSUE TITLE
typos in the `Primitives.sol` contract

### ISSUE THREAD

**Issue by amidmm** [solidity-by-example/solidity-by-example.github.io#274]
There are cases in [`Primitives.sol`](https://github.com/solidity-by-example/solidity-by-example.github.io/blob/gh-pages/contracts/src/primitives/Primitives.sol) the comment refers to `uint` and `int`, however, in code `uint256` and `int256` has been used instead.

**Comment by t4sk** [comment]
the code formatter (`forge fmt`) automatically change uint into uint256.
I don't want to constantly fix this so I will let the formatter do it's thing and leave a comment saying "uint is alias for uint256"

**Comment by amidmm** [comment]
I don't know if it would be confusing in the tutorial or not, but you can use `// forgefmt: disable-next-line` to prevent the automatic change.
